# Default values for yp-rover.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  replicaCount: 1

worker:
  replicaCount: 2

image:
  repository: innovate/yp-rover
  # tag: latest
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
